---
title: "hongru Tang"
author: "ht2611"
date: "2022-12-03"
output: github_document
---

## data clean

```{r}
library(tidyverse)
library(purrr)
library(modelr)
library(dbplyr)
library(plyr)
```

```{r}
setwd(dir="./Data_preprocessing/data")
a <- list.files()     
a 
dir <- paste("./",a,sep="")                 
n <- length(dir) 
merge_data <- read.csv(file = dir[1],header=T,sep=",")   
merge_data <- cbind(dir[1], merge_data )
merge_data <- rename(merge_data, c("dir[1]"="yyyymm"))
for (i in 2:7){
  new.data <- read.csv(file = dir[i], header=T, sep=",")
  new.data <- cbind(dir[i], new.data)
  new.data <- rename(new.data, c("dir[i]"="yyyymm"))
  merge_data <- rbind(merge_data,new.data)
}
```

## data clean, drop data with unknown
```{r}
# filter data with unknown
tidydata1=merge_data%>%
  na.omit()%>%
  filter(!susp_sex=="U")%>%
  filter(!susp_race=="UNKNOWN")%>%
  filter(!susp_age_group=="UNKNOWN")%>%
   filter(!vic_race=="UNKNOWN")%>%
  filter(!vic_age_group=="UNKNOWN")%>%
  separate(date,into=c("mon","day","year"),sep="/")%>%
  mutate(jurisdiction_code=as.numeric(jurisdiction_code))%>%
  mutate(susp_sex=ifelse(susp_sex=="M",1,0),vic_sex=ifelse(vic_sex=="M",1,0),jurisdiction_code=ifelse(jurisdiction_code>=3,3,jurisdiction_code+0))%>%
  mutate(jurisdiction_code=as.factor(jurisdiction_code))%>%
  mutate(covid_state=ifelse(year>=2020,1,0))
# when year >=2020, we assume the world is in a covid state.
```

## susp sex is a predictor, use logisitc regression

```{r}
mylogit <- glm(susp_sex ~ precinct
 + borough + jurisdiction_code+atpt_cptd
+level+susp_age_group
+susp_race+vic_age_group+vic_race+vic_sex+covid_state, data = tidydata1, family = "binomial")
# almost full model except victor information
mylogit%>%
  broom::tidy() %>% 
  select(term, estimate, p.value)
```
For backward stepwise, in order to select variables.

```{r}
step(mylogit, direction='backward')
```

Through backward, we found that we need all the variables.(lasso?)


```{r}
# 此图不要
tidydata1 %>% 
  add_predictions(mylogit) %>% 
  ggplot(aes(x = borough, y = susp_sex)) + geom_point() + 
  geom_line(aes(y = pred), color = "red")
```


```{r}
tidydata1 %>% 
  modelr::add_residuals(mylogit) %>% 
  ggplot(aes(x = borough, y = resid)) + geom_violin()+
   facet_wrap(~covid_state)+theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
tidydata1 %>% 
  modelr::add_residuals(mylogit) %>% 
  ggplot(aes(x = level, y = resid)) + geom_violin()+facet_wrap(~covid_state)
```

```{r}
tidydata1 %>% 
  modelr::add_residuals(mylogit) %>% 
  ggplot(aes(x = susp_age_group, y = resid)) + geom_violin()+facet_wrap(~covid_state)
```

```{r}
tidydata1 %>% 
  modelr::add_residuals(mylogit) %>% 
  ggplot(aes(x = susp_race, y = resid)) + geom_violin()+
  theme(axis.text.x = element_text(angle = 80, hjust = 1))+facet_wrap(~covid_state)
```

## susp race is a predictor
```{r}
# There are lot of race, we only focus on white and black
tidydata2=tidydata1%>%
  filter(susp_race %in% c("BLACK","WHITE"))%>%
  mutate(susp_race=ifelse(susp_race=="BLACK",1,0))
```

```{r}
mylogit_2=glm(susp_race ~ precinct
 + borough + jurisdiction_code+atpt_cptd
+level+susp_age_group
+susp_sex+vic_age_group+vic_race+vic_sex, data = tidydata2, family = "binomial")
# almost full model except victor information
mylogit_2%>%
  broom::tidy() %>% 
  select(term, estimate, p.value)
```

```{r}
tidydata2 %>% 
  modelr::add_residuals(mylogit_2) %>% 
  ggplot(aes(x = borough, y = resid)) + geom_violin()+facet_wrap(~covid_state)+theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
tidydata2 %>% 
  modelr::add_residuals(mylogit_2) %>% 
  ggplot(aes(x = level, y = resid)) + geom_violin()+facet_wrap(~covid_state)
```

```{r}
tidydata2 %>% 
  modelr::add_residuals(mylogit_2) %>% 
  ggplot(aes(x = susp_age_group, y = resid)) + geom_violin()+facet_wrap(~covid_state)
```